#!/usr/bin/env bash
#MISE description="Set global git config"
set -euo pipefail

echo "[base] Updating global git config"
git config --global init.defaultBranch main
git config --global pull.rebase false
git config --global user.email juliocesarmfo@gmail.com
git config --global user.name jliocsar
git config --global core.pager "hunk pager"
git config --global merge.conflictStyle zdiff3
